
var AliaDemos = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(AliaDemos) {
  AliaDemos = AliaDemos || {};

var e;e||(e=typeof AliaDemos !== 'undefined' ? AliaDemos : {});var aa={},da;for(da in e)e.hasOwnProperty(da)&&(aa[da]=e[da]);var ea="./this.program",r="";document.currentScript&&(r=document.currentScript.src);_scriptDir&&(r=_scriptDir);0!==r.indexOf("blob:")?r=r.substr(0,r.lastIndexOf("/")+1):r="";var fa=e.print||console.log.bind(console),v=e.printErr||console.warn.bind(console);for(da in aa)aa.hasOwnProperty(da)&&(e[da]=aa[da]);aa=null;e.thisProgram&&(ea=e.thisProgram);
function ha(a){ia||(ia={});ia[a]||(ia[a]=1,v(a))}var ia,ja={};function ka(a){if(a){la("vi");ja.vi||(ja.vi={});var b=ja.vi;b[a]||(b[a]=function(c){return(c=[c],c.length)?e.dynCall_vi.apply(null,[a].concat(c)):e.dynCall_vi.call(null,a)});return b[a]}}var w=0,ma;e.wasmBinary&&(ma=e.wasmBinary);var na;e.noExitRuntime&&(na=e.noExitRuntime);"object"!==typeof WebAssembly&&v("no native wasm support detected");var oa,pa=new WebAssembly.Table({initial:2814,maximum:2814,element:"anyfunc"}),qa=!1;
function la(a,b){a||z("Assertion failed: "+b)}function ra(a){var b=e["_"+a];la(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function sa(a,b,c,d){var f={string:function(m){var q=0;if(null!==m&&void 0!==m&&0!==m){var t=(m.length<<2)+1;q=ta(t);A(m,B,q,t)}return q},array:function(m){var q=ta(m.length);C.set(m,q);return q}},g=ra(a),h=[];a=0;if(d)for(var k=0;k<d.length;k++){var n=f[c[k]];n?(0===a&&(a=E()),h[k]=n(d[k])):h[k]=d[k]}c=g.apply(null,h);c=function(m){return"string"===b?G(m):"boolean"===b?!!m:m}(c);0!==a&&J(a);return c}var ua="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function va(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ua)return ua.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function G(a,b){return a?va(B,a,b):""}
function A(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var xa,C,B,ya,K,L,M,za,Aa,Ba=e.TOTAL_MEMORY||16777216;e.wasmMemory?oa=e.wasmMemory:oa=new WebAssembly.Memory({initial:Ba/65536,maximum:Ba/65536});oa&&(xa=oa.buffer);Ba=xa.byteLength;var N=xa;xa=N;e.HEAP8=C=new Int8Array(N);e.HEAP16=ya=new Int16Array(N);
e.HEAP32=L=new Int32Array(N);e.HEAPU8=B=new Uint8Array(N);e.HEAPU16=K=new Uint16Array(N);e.HEAPU32=M=new Uint32Array(N);e.HEAPF32=za=new Float32Array(N);e.HEAPF64=Aa=new Float64Array(N);L[33740]=5378032;function Ca(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.wc;"number"===typeof c?void 0===b.Zb?e.dynCall_v(c):e.dynCall_vi(c,b.Zb):c(void 0===b.Zb?null:b.Zb)}}}var Da=[],Ea=[],Fa=[],Ga=[];function Ha(){var a=e.preRun.shift();Da.unshift(a)}
var Ia=Math.abs,Ja=Math.ceil,Ka=Math.floor,La=Math.min,Ma=0,Na=null,Oa=null;function Pa(){Ma++;e.monitorRunDependencies&&e.monitorRunDependencies(Ma)}function Qa(){Ma--;e.monitorRunDependencies&&e.monitorRunDependencies(Ma);if(0==Ma&&(null!==Na&&(clearInterval(Na),Na=null),Oa)){var a=Oa;Oa=null;a()}}e.preloadedImages={};e.preloadedAudios={};function z(a){if(e.onAbort)e.onAbort(a);fa(a);v(a);qa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function Ra(){var a=Sa;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Sa="demos.wasm";if(!Ra()){var Ta=Sa;Sa=e.locateFile?e.locateFile(Ta,r):r+Ta}function Ua(){try{if(ma)return new Uint8Array(ma);throw"both async and sync fetching of the wasm failed";}catch(a){z(a)}}
function Va(){return ma||"function"!==typeof fetch?new Promise(function(a){a(Ua())}):fetch(Sa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Sa+"'";return a.arrayBuffer()}).catch(function(){return Ua()})}
var Wa,Xa,Ya={98875:function(a,b){e.removeAttribute(a,e.UTF8ToString(b))},98940:function(a,b,c){e.setAttribute(a,e.UTF8ToString(b),e.UTF8ToString(c))},99037:function(a){e.Wb[a].asmDomRaws=[]},99080:function(a,b){e.Wb[a].asmDomRaws.push(e.UTF8ToString(b))},99163:function(a,b){b=e.UTF8ToString(b).replace(/^on/,"");a=e.Wb[a];a.removeEventListener(b,e.jc,!1);delete a.asmDomEvents[b]},99343:function(a,b){a=e.Wb[a];a.Hc=b;void 0===a.asmDomEvents&&(a.asmDomEvents={})},99469:function(a,b){b=e.UTF8ToString(b).replace(/^on/,
"");a=e.Wb[a];a.addEventListener(b,e.jc,!1);a.asmDomEvents[b]=e.jc},99659:function(a,b){return 0===b?e.createElement(e.UTF8ToString(a)):e.createElementNS(e.UTF8ToString(b),e.UTF8ToString(a))},99819:function(a){return e.createTextNode(e.UTF8ToString(a))},99885:function(){return e.createDocumentFragment()},99930:function(a){return e.createComment(e.UTF8ToString(a))},99993:function(a,b){e.appendChild(a,b)},100028:function(a,b,c){e.insertBefore(a,b,c)},100068:function(a){e.removeChild(a)},100096:function(a,
b,c){e.insertBefore(a,b,e.nextSibling(c))},100155:function(a,b,c){e.insertBefore(a,b,c)},100192:function(a,b){e.Sc(a,e.UTF8ToString(b))},100251:function(a,b){var c=e.parentNode(b);0!==c&&(e.insertBefore(c,a,e.nextSibling(b)),e.removeChild(b))},100396:function(){window.asmDomHelpers.eventProxy=function(a){return e.functionCallback(this.Hc,a.type,a)};e.ad=window.asmDomHelpers.domApi.addNode;e.createElement=window.asmDomHelpers.domApi.createElement;e.createElementNS=window.asmDomHelpers.domApi.createElementNS;
e.createTextNode=window.asmDomHelpers.domApi.createTextNode;e.createComment=window.asmDomHelpers.domApi.createComment;e.createDocumentFragment=window.asmDomHelpers.domApi.createDocumentFragment;e.insertBefore=window.asmDomHelpers.domApi.insertBefore;e.removeChild=window.asmDomHelpers.domApi.removeChild;e.appendChild=window.asmDomHelpers.domApi.appendChild;e.removeAttribute=window.asmDomHelpers.domApi.removeAttribute;e.setAttribute=window.asmDomHelpers.domApi.setAttribute;e.parentNode=window.asmDomHelpers.domApi.parentNode;
e.nextSibling=window.asmDomHelpers.domApi.nextSibling;e.Sc=window.asmDomHelpers.domApi.setNodeValue;e.Wb=window.asmDomHelpers.nodes;e.jc=window.asmDomHelpers.eventProxy}};Ea.push({wc:function(){Za()}});var O={},$a=[];function ab(a){if(!a||O[a])return a;for(var b in O)for(var c=+b,d=O[c].ic,f=d.length,g=0;g<f;g++)if(d[g]===a)return c;return a}var bb=0;function cb(a){try{return P(a)}catch(b){}}function db(a){e.___errno_location&&(L[e.___errno_location()>>2]=a)}
function eb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function fb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=eb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function hb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ib(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=eb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var jb=[];function kb(a,b){jb[a]={input:[],Gb:[],Sb:b};lb(a,mb)}
var mb={open:function(a){var b=jb[a.node.cc];if(!b)throw new Q(43);a.Ib=b;a.seekable=!1},close:function(a){a.Ib.Sb.flush(a.Ib)},flush:function(a){a.Ib.Sb.flush(a.Ib)},read:function(a,b,c,d){if(!a.Ib||!a.Ib.Sb.xc)throw new Q(60);for(var f=0,g=0;g<d;g++){try{var h=a.Ib.Sb.xc(a.Ib)}catch(k){throw new Q(29);}if(void 0===h&&0===f)throw new Q(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.Ib||!a.Ib.Sb.lc)throw new Q(60);try{for(var f=
0;f<d;f++)a.Ib.Sb.lc(a.Ib,b[c+f])}catch(g){throw new Q(29);}d&&(a.node.timestamp=Date.now());return f}},ob={xc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=nb(b,!0)}return a.input.shift()},lc:function(a,b){null===b||10===b?(fa(va(a.Gb,0)),a.Gb=[]):0!=b&&a.Gb.push(b)},flush:function(a){a.Gb&&0<a.Gb.length&&
(fa(va(a.Gb,0)),a.Gb=[])}},pb={lc:function(a,b){null===b||10===b?(v(va(a.Gb,0)),a.Gb=[]):0!=b&&a.Gb.push(b)},flush:function(a){a.Gb&&0<a.Gb.length&&(v(va(a.Gb,0)),a.Gb=[])}},R={Jb:null,Mb:function(){return R.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Q(63);R.Jb||(R.Jb={dir:{node:{Ob:R.Db.Ob,Lb:R.Db.Lb,Vb:R.Db.Vb,$b:R.Db.$b,Cc:R.Db.Cc,Ec:R.Db.Ec,Dc:R.Db.Dc,Bc:R.Db.Bc,ec:R.Db.ec},stream:{Qb:R.Eb.Qb}},file:{node:{Ob:R.Db.Ob,Lb:R.Db.Lb},
stream:{Qb:R.Eb.Qb,read:R.Eb.read,write:R.Eb.write,oc:R.Eb.oc,yc:R.Eb.yc,bc:R.Eb.bc}},link:{node:{Ob:R.Db.Ob,Lb:R.Db.Lb,Xb:R.Db.Xb},stream:{}},qc:{node:{Ob:R.Db.Ob,Lb:R.Db.Lb},stream:qb}});c=rb(a,b,c,d);16384===(c.mode&61440)?(c.Db=R.Jb.dir.node,c.Eb=R.Jb.dir.stream,c.Cb={}):32768===(c.mode&61440)?(c.Db=R.Jb.file.node,c.Eb=R.Jb.file.stream,c.Fb=0,c.Cb=null):40960===(c.mode&61440)?(c.Db=R.Jb.link.node,c.Eb=R.Jb.link.stream):8192===(c.mode&61440)&&(c.Db=R.Jb.qc.node,c.Eb=R.Jb.qc.stream);c.timestamp=
Date.now();a&&(a.Cb[b]=c);return c},jd:function(a){if(a.Cb&&a.Cb.subarray){for(var b=[],c=0;c<a.Fb;++c)b.push(a.Cb[c]);return b}return a.Cb},kd:function(a){return a.Cb?a.Cb.subarray?a.Cb.subarray(0,a.Fb):new Uint8Array(a.Cb):new Uint8Array},tc:function(a,b){var c=a.Cb?a.Cb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Cb,a.Cb=new Uint8Array(b),0<a.Fb&&a.Cb.set(c.subarray(0,a.Fb),0))},Qc:function(a,b){if(a.Fb!=b)if(0==b)a.Cb=null,a.Fb=0;else{if(!a.Cb||a.Cb.subarray){var c=
a.Cb;a.Cb=new Uint8Array(new ArrayBuffer(b));c&&a.Cb.set(c.subarray(0,Math.min(b,a.Fb)))}else if(a.Cb||(a.Cb=[]),a.Cb.length>b)a.Cb.length=b;else for(;a.Cb.length<b;)a.Cb.push(0);a.Fb=b}},Db:{Ob:function(a){var b={};b.gd=8192===(a.mode&61440)?a.id:1;b.md=a.id;b.mode=a.mode;b.sd=1;b.uid=0;b.ld=0;b.cc=a.cc;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Fb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.bd=new Date(a.timestamp);b.rd=new Date(a.timestamp);b.fd=new Date(a.timestamp);
b.Ic=4096;b.cd=Math.ceil(b.size/b.Ic);return b},Lb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&R.Qc(a,b.size)},Vb:function(){throw sb[44];},$b:function(a,b,c,d){return R.createNode(a,b,c,d)},Cc:function(a,b,c){if(16384===(a.mode&61440)){try{var d=tb(b,c)}catch(g){}if(d)for(var f in d.Cb)throw new Q(55);}delete a.parent.Cb[a.name];a.name=c;b.Cb[c]=a;a.parent=b},Ec:function(a,b){delete a.Cb[b]},Dc:function(a,b){var c=tb(a,b),d;for(d in c.Cb)throw new Q(55);
delete a.Cb[b]},Bc:function(a){var b=[".",".."],c;for(c in a.Cb)a.Cb.hasOwnProperty(c)&&b.push(c);return b},ec:function(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},Xb:function(a){if(40960!==(a.mode&61440))throw new Q(28);return a.link}},Eb:{read:function(a,b,c,d,f){var g=a.node.Cb;if(f>=a.node.Fb)return 0;a=Math.min(a.node.Fb-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();
if(b.subarray&&(!a.Cb||a.Cb.subarray)){if(g)return a.Cb=b.subarray(c,c+d),a.Fb=d;if(0===a.Fb&&0===f)return a.Cb=new Uint8Array(b.subarray(c,c+d)),a.Fb=d;if(f+d<=a.Fb)return a.Cb.set(b.subarray(c,c+d),f),d}R.tc(a,f+d);if(a.Cb.subarray&&b.subarray)a.Cb.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Cb[f+g]=b[c+g];a.Fb=Math.max(a.Fb,f+d);return d},Qb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Fb);if(0>b)throw new Q(28);return b},oc:function(a,b,c){R.tc(a.node,
b+c);a.node.Fb=Math.max(a.node.Fb,b+c)},yc:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new Q(43);c=a.node.Cb;if(h&2||c.buffer!==b.buffer){if(0<f||f+d<a.node.Fb)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;f=b.buffer==C.buffer;d=ub(d);if(!d)throw new Q(48);(f?C:b).set(c,d)}else a=!1,d=c.byteOffset;return{Oc:d,Fc:a}},bc:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new Q(43);if(f&2)return 0;R.Eb.write(a,b,0,d,c,!1);return 0}}},vb=null,wb={},xb=
[],yb=1,zb=null,Ab=!0,Bb={},Q=null,sb={};
function Cb(a,b){a=ib("/",a);b=b||{};if(!a)return{path:"",node:null};var c={vc:!0,mc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.mc)throw new Q(32);a=eb(a.split("/").filter(function(h){return!!h}),!1);var f=vb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=tb(f,a[d]);c=fb(c+"/"+a[d]);f.ac&&(!g||g&&b.vc)&&(f=f.ac.root);if(!g||b.uc)for(g=0;40960===(f.mode&61440);)if(f=Db(c),c=ib(gb(c),f),f=Cb(c,{mc:b.mc}).node,40<g++)throw new Q(32);}return{path:c,node:f}}
function Eb(a){for(var b;;){if(a===a.parent)return a=a.Mb.zc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Fb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zb.length}function Gb(a){var b=Fb(a.parent.id,a.name);a.Nc=zb[b];zb[b]=a}function tb(a,b){var c;if(c=(c=Hb(a,"x"))?c:a.Db.Vb?0:2)throw new Q(c,a);for(c=zb[Fb(a.id,b)];c;c=c.Nc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Db.Vb(a,b)}
function rb(a,b,c,d){Ib||(Ib=function(f,g,h,k){f||(f=this);this.parent=f;this.Mb=f.Mb;this.ac=null;this.id=yb++;this.name=g;this.mode=h;this.Db={};this.Eb={};this.cc=k},Ib.prototype={},Object.defineProperties(Ib.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(f){f?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(f){f?this.mode|=146:this.mode&=-147}}}));a=new Ib(a,b,c,d);Gb(a);return a}
var Jb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Kb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Hb(a,b){if(Ab)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Lb(a,b){try{return tb(a,b),20}catch(c){}return Hb(a,"wx")}
function Mb(){var a=4096;for(var b=0;b<=a;b++)if(!xb[b])return b;throw new Q(33);}function Nb(a){Ob||(Ob=function(){},Ob.prototype={},Object.defineProperties(Ob.prototype,{object:{get:function(){return this.node},set:function(d){this.node=d}}}));var b=new Ob,c;for(c in a)b[c]=a[c];a=b;b=Mb();a.Pb=b;return xb[b]=a}var qb={open:function(a){a.Eb=wb[a.node.cc].Eb;a.Eb.open&&a.Eb.open(a)},Qb:function(){throw new Q(70);}};function lb(a,b){wb[a]={Eb:b}}
function Pb(a,b){var c="/"===b,d=!b;if(c&&vb)throw new Q(10);if(!c&&!d){var f=Cb(b,{vc:!1});b=f.path;f=f.node;if(f.ac)throw new Q(10);if(16384!==(f.mode&61440))throw new Q(54);}b={type:a,vd:{},zc:b,Mc:[]};a=a.Mb(b);a.Mb=b;b.root=a;c?vb=a:f&&(f.ac=b,f.Mb&&f.Mb.Mc.push(b))}function Qb(a,b,c){var d=Cb(a,{parent:!0}).node;a=hb(a);if(!a||"."===a||".."===a)throw new Q(28);var f=Lb(d,a);if(f)throw new Q(f);if(!d.Db.$b)throw new Q(63);return d.Db.$b(d,a,b,c)}function S(a){Qb(a,16895,0)}
function Rb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Qb(a,b|8192,c)}function Sb(a,b){if(!ib(a))throw new Q(44);var c=Cb(b,{parent:!0}).node;if(!c)throw new Q(44);b=hb(b);var d=Lb(c,b);if(d)throw new Q(d);if(!c.Db.ec)throw new Q(63);c.Db.ec(c,b,a)}function Db(a){a=Cb(a).node;if(!a)throw new Q(44);if(!a.Db.Xb)throw new Q(28);return ib(Eb(a.parent),a.Db.Xb(a))}
function Tb(a,b){if(""===a)throw new Q(44);if("string"===typeof b){var c=Jb[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var f=a;else{a=fb(a);try{f=Cb(a,{uc:!(b&131072)}).node}catch(h){}}c=!1;if(b&64)if(f){if(b&128)throw new Q(20);}else f=Qb(a,d,0),c=!0;if(!f)throw new Q(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new Q(54);if(!c&&(d=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Kb(b)||b&512)?31:Hb(f,Kb(b)):44))throw new Q(d);if(b&512){d=f;var g;"string"===typeof d?g=Cb(d,{uc:!0}).node:g=d;if(!g.Db.Lb)throw new Q(63);if(16384===(g.mode&61440))throw new Q(31);if(32768!==(g.mode&61440))throw new Q(28);if(d=Hb(g,"w"))throw new Q(d);g.Db.Lb(g,{size:0,timestamp:Date.now()})}b&=-641;f=Nb({node:f,path:Eb(f),flags:b,seekable:!0,position:0,Eb:f.Eb,Xc:[],error:!1});f.Eb.open&&f.Eb.open(f);!e.logReadFiles||b&1||(Ub||(Ub={}),a in Ub||(Ub[a]=1,v("FS.trackingDelegate error on read file: "+
a)));try{Bb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Bb.onOpenFile(a,f))}catch(h){v("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}}function Vb(a,b,c){if(null===a.Pb)throw new Q(8);if(!a.seekable||!a.Eb.Qb)throw new Q(70);if(0!=c&&1!=c&&2!=c)throw new Q(28);a.position=a.Eb.Qb(a,b,c);a.Xc=[]}
function Wb(){Q||(Q=function(a,b){this.node=b;this.Rc=function(c){this.Ub=c};this.Rc(a);this.message="FS error"},Q.prototype=Error(),Q.prototype.constructor=Q,[44].forEach(function(a){sb[a]=new Q(a);sb[a].stack="<generic error, no stack>"}))}var Xb;function Yb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Zb(a,b,c){a=fb("/dev/"+a);var d=Yb(!!b,!!c);$b||($b=64);var f=$b++<<8|0;lb(f,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,h,k,n){for(var m=0,q=0;q<n;q++){try{var t=b()}catch(y){throw new Q(29);}if(void 0===t&&0===m)throw new Q(6);if(null===t||void 0===t)break;m++;h[k+q]=t}m&&(g.node.timestamp=Date.now());return m},write:function(g,h,k,n){for(var m=0;m<n;m++)try{c(h[k+m])}catch(q){throw new Q(29);}n&&(g.node.timestamp=Date.now());return m}});
Rb(a,d,f)}var $b,ac={},Ib,Ob,Ub,bc={},cc=0;function dc(){cc+=4;return L[cc-4>>2]}function ec(a){void 0===a&&(a=dc());a=xb[a];if(!a)throw new Q(8);return a}function fc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var gc=void 0;function T(a){for(var b="";B[a];)b+=gc[B[a++]];return b}var hc={},ic={},jc={};
function kc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function lc(a,b){a=kc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function mc(a){var b=Error,c=lc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var nc=void 0;function U(a){throw new nc(a);}var oc=void 0;
function pc(a,b){function c(k){k=b(k);if(k.length!==d.length)throw new oc("Mismatched type converter count");for(var n=0;n<d.length;++n)W(d[n],k[n])}var d=[];d.forEach(function(k){jc[k]=a});var f=Array(a.length),g=[],h=0;a.forEach(function(k,n){ic.hasOwnProperty(k)?f[n]=ic[k]:(g.push(k),hc.hasOwnProperty(k)||(hc[k]=[]),hc[k].push(function(){f[n]=ic[k];++h;h===g.length&&c(f)}))});0===g.length&&c(f)}
function W(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||U('type "'+d+'" must have a positive integer typeid pointer');if(ic.hasOwnProperty(a)){if(c.Kc)return;U("Cannot register type '"+d+"' twice")}ic[a]=b;delete jc[a];hc.hasOwnProperty(a)&&(b=hc[a],delete hc[a],b.forEach(function(f){f()}))}var qc=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function rc(a){4<a&&0===--X[a].Rb&&(X[a]=void 0,qc.push(a))}function sc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=qc.length?qc.pop():X.length;X[b]={Rb:1,value:a};return b}}function tc(a){return this.fromWireType(M[a>>2])}function uc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function vc(a,b){switch(b){case 2:return function(c){return this.fromWireType(za[c>>2])};case 3:return function(c){return this.fromWireType(Aa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function wc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=lc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function xc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function yc(a,b){var c=e;if(void 0===c[a].Kb){var d=c[a];c[a]=function(){c[a].Kb.hasOwnProperty(arguments.length)||U("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].Kb+")!");return c[a].Kb[arguments.length].apply(this,arguments)};c[a].Kb=[];c[a].Kb[d.Gc]=d}}
function zc(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].Kb&&void 0!==e[a].Kb[c])&&U("Cannot register public name '"+a+"' twice"),yc(a,a),e.hasOwnProperty(c)&&U("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].Kb[c]=b):(e[a]=b,void 0!==c&&(e[a].ud=c))}function Ac(a,b){for(var c=[],d=0;d<a;d++)c.push(L[(b>>2)+d]);return c}
function Bc(a,b){a=T(a);if(void 0!==e["FUNCTION_TABLE_"+a])var c=e["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=e["dynCall_"+a];void 0===c&&(c=e["dynCall_"+a.replace(/f/g,"d")],void 0===c&&U("No dynCall invoker for signature: "+a));for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",
f+"};\n"))(c,b)}"function"!==typeof c&&U("unknown function pointer with signature "+a+": "+b);return c}var Cc=void 0;function Dc(a){a=Ec(a);var b=T(a);P(a);return b}function Fc(a,b){function c(g){f[g]||ic[g]||(jc[g]?jc[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new Cc(a+": "+d.map(Dc).join([", "]));}
function Gc(a,b,c){switch(b){case 0:return c?function(d){return C[d]}:function(d){return B[d]};case 1:return c?function(d){return ya[d>>1]}:function(d){return K[d>>1]};case 2:return c?function(d){return L[d>>2]}:function(d){return M[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Hc(a){a||U("Cannot use deleted val. handle = "+a);return X[a].value}function Ic(a,b){var c=ic[a];void 0===c&&U(b+" has unknown type "+Dc(a));return c}var Jc={};
function Kc(a){var b=Jc[a];return void 0===b?T(a):b}var Lc=[];function Mc(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Nc(a){var b=Lc.length;Lc.push(a);return b}function Oc(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Ic(L[(b>>2)+d],"parameter "+d);return c}function Pc(){z()}
function Qc(a,b){Rc=a;Sc=b;if(Tc)if(0==a)Uc=function(){var d=Math.max(0,Vc+b-Pc())|0;setTimeout(Wc,d)};else if(1==a)Uc=function(){Xc(Wc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}Uc=function(){setImmediate(Wc)}}}
function Yc(a){var b=Zc;na=!0;la(!Tc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Tc=a;Zc=b;var c="undefined"!==typeof b?function(){e.dynCall_vi(a,b)}:function(){e.dynCall_v(a)};var d=$c;Wc=function(){if(!qa)if(0<ad.length){var f=Date.now(),g=ad.shift();g.wc(g.Zb);if(bd){var h=bd,k=0==h%1?h-1:Math.floor(h);bd=g.dd?k:(8*h+(k+.5))/9}console.log('main loop blocker "'+
g.name+'" took '+(Date.now()-f)+" ms");e.setStatus&&(f=e.statusMessage||"Please wait...",g=bd,h=cd.hd,g?g<h?e.setStatus(f+" ("+(h-g)+"/"+h+")"):e.setStatus(f):e.setStatus(""));d<$c||setTimeout(Wc,0)}else if(!(d<$c))if(dd=dd+1|0,1==Rc&&1<Sc&&0!=dd%Sc)Uc();else{0==Rc&&(Vc=Pc());if(!(qa||e.preMainLoop&&!1===e.preMainLoop())){try{c()}catch(n){throw n&&"object"===typeof n&&n.stack&&v("exception thrown: "+[n,n.stack]),n;}e.postMainLoop&&e.postMainLoop()}d<$c||("object"===typeof SDL&&SDL.audio&&SDL.audio.Pc&&
SDL.audio.Pc(),Uc())}}}var Uc=null,$c=0,Tc=null,Zc=0,Rc=0,Sc=0,dd=0,ad=[],cd={},Vc,Wc,bd,ed=!1,fd=!1,gd=[];
function hd(){function a(){fd=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!id){id=!0;try{jd=!0}catch(c){jd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}kd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:jd?null:console.log("warning: no BlobBuilder");
ld="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;e.Ac||"undefined"!==typeof ld||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.Ac=!0);e.preloadPlugins.push({canHandle:function(c){return!e.Ac&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,f,g){var h=null;if(jd)try{h=new Blob([c],{type:md(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:md(d)}))}catch(m){ha("Blob constructor present but fails: "+
m+"; falling back to blob builder")}h||(h=new kd,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var k=ld.createObjectURL(h),n=new Image;n.onload=function(){la(n.complete,"Image "+d+" could not be decoded");var m=document.createElement("canvas");m.width=n.width;m.height=n.height;m.getContext("2d").drawImage(n,0,0);e.preloadedImages[d]=m;ld.revokeObjectURL(k);f&&f(c)};n.onerror=function(){console.log("Image "+k+" could not be decoded");g&&g()};n.src=k}});e.preloadPlugins.push({canHandle:function(c){return!e.td&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,f,g){function h(t){n||(n=!0,e.preloadedAudios[d]=t,f&&f(c))}function k(){n||(n=!0,e.preloadedAudios[d]=new Audio,g&&g())}var n=!1;if(jd){try{var m=new Blob([c],{type:md(d)})}catch(t){return k()}m=ld.createObjectURL(m);var q=new Audio;q.addEventListener("canplaythrough",function(){h(q)},!1);q.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var t="",y=0,l=0,
p=0;p<c.length;p++)for(y=y<<8|c[p],l+=8;6<=l;){var x=y>>l-6&63;l-=6;t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==l?(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(y&3)<<4],t+="=="):4==l&&(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(y&15)<<2],t+="=");q.src="data:audio/x-"+d.substr(-3)+";base64,"+t;h(q)}};q.src=m;nd(function(){h(q)},1E4)}else return k()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||
b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,
!1),e.elementPointerLock&&b.addEventListener("click",function(c){!fd&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function od(a,b,c,d){if(b&&e.rc&&a==e.canvas)return e.rc;var f;if(b){var g={antialias:!1,alpha:!1,od:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof GL&&(f=GL.ed(a,g)))var k=GL.getContext(f).$c}else k=a.getContext("2d");if(!k)return null;c&&(b||la("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.rc=k,b&&GL.pd(f),e.xd=b,gd.forEach(function(n){n()}),hd());return k}var pd=!1,qd=void 0,rd=void 0;
function sd(a,b,c){function d(){ed=!1;var h=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===h?(f.exitFullscreen=td,qd&&f.requestPointerLock(),ed=!0,rd?("undefined"!=typeof SDL&&(L[SDL.screen>>2]=M[SDL.screen>>2]|8388608),ud(e.canvas),vd()):ud(f)):(h.parentNode.insertBefore(f,h),h.parentNode.removeChild(h),rd?("undefined"!=typeof SDL&&(L[SDL.screen>>2]=M[SDL.screen>>2]&
-8388609),ud(e.canvas),vd()):ud(f));if(e.onFullScreen)e.onFullScreen(ed);if(e.onFullscreen)e.onFullscreen(ed)}qd=a;rd=b;wd=c;"undefined"===typeof qd&&(qd=!0);"undefined"===typeof rd&&(rd=!1);"undefined"===typeof wd&&(wd=null);var f=e.canvas;pd||(pd=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");
f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.requestFullscreen({yd:c}):g.requestFullscreen()}
function td(){if(!ed)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var xd=0;function Xc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===xd)xd=b+1E3/60;else for(;b+2>=xd;)xd+=1E3/60;setTimeout(a,Math.max(xd-b,0))}}function yd(a){Xc(function(){qa||a()})}
function nd(a,b){na=!0;setTimeout(function(){qa||a()},b)}function md(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var zd=[];function vd(){var a=e.canvas;zd.forEach(function(b){b(a.width,a.height)})}
function ud(a,b,c){b&&c?(a.Yc=b,a.Jc=c):(b=a.Yc,c=a.Jc);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*
g)}rd?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var id,jd,kd,ld,wd,Ad=[];function Y(a,b){M[a>>2]=b;M[a+4>>2]=b/4294967296|0}var Bd;
function Cd(a,b,c,d,f){var g=M[a+8>>2];if(g){var h=G(g),k=a+112,n=G(k);n||(n="GET");var m=M[k+52>>2],q=M[k+56>>2],t=!!M[k+60>>2],y=M[k+68>>2],l=M[k+72>>2];g=M[k+76>>2];var p=M[k+80>>2],x=M[k+84>>2];k=M[k+88>>2];var F=!!(m&1),H=!!(m&2);m=!!(m&64);y=y?G(y):void 0;l=l?G(l):void 0;var V=p?G(p):void 0,u=new XMLHttpRequest;u.withCredentials=t;u.open(n,h,!m,y,l);m||(u.timeout=q);u.Zc=h;la(!H,"streaming uses moz-chunked-arraybuffer which is no longer supported; TODO: rewrite using fetch()");u.responseType=
"arraybuffer";p&&u.overrideMimeType(V);if(g)for(;;){n=M[g>>2];if(!n)break;h=M[g+4>>2];if(!h)break;g+=8;n=G(n);h=G(h);u.setRequestHeader(n,h)}Ad.push(u);M[a+0>>2]=Ad.length;g=x&&k?B.slice(x,x+k):null;u.onload=function(I){var D=u.response?u.response.byteLength:0,ba=0,ca=0;F&&!H&&(ca=D,ba=ub(ca),B.set(new Uint8Array(u.response),ba));M[a+12>>2]=ba;Y(a+16,ca);Y(a+24,0);D&&Y(a+32,D);K[a+40>>1]=u.readyState;4===u.readyState&&0===u.status&&(u.status=0<D?200:404);K[a+42>>1]=u.status;u.statusText&&A(u.statusText,
B,a+44,64);200<=u.status&&300>u.status?b&&b(a,u,I):c&&c(a,u,I)};u.onerror=function(I){var D=u.status;4===u.readyState&&0===D&&(D=404);M[a+12>>2]=0;Y(a+16,0);Y(a+24,0);Y(a+32,0);K[a+40>>1]=u.readyState;K[a+42>>1]=D;c&&c(a,u,I)};u.ontimeout=function(I){c&&c(a,u,I)};u.onprogress=function(I){var D=F&&H&&u.response?u.response.byteLength:0,ba=0;F&&H&&(ba=ub(D),B.set(new Uint8Array(u.response),ba));M[a+12>>2]=ba;Y(a+16,D);Y(a+24,I.loaded-D);Y(a+32,I.total);K[a+40>>1]=u.readyState;3<=u.readyState&&0===u.status&&
0<I.loaded&&(u.status=200);K[a+42>>1]=u.status;u.statusText&&A(u.statusText,B,a+44,64);d&&d(a,u,I)};u.onreadystatechange=function(I){K[a+40>>1]=u.readyState;2<=u.readyState&&(K[a+42>>1]=u.status);f&&f(a,u,I)};try{u.send(g)}catch(I){c&&c(a,u,I)}}else c(a,0,"no url specified!")}
function Dd(a,b,c,d){var f=Bd;if(f){var g=M[a+112+64>>2];g||(g=M[a+8>>2]);var h=G(g);try{var k=f.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);k.onsuccess=function(){K[a+40>>1]=4;K[a+42>>1]=200;A("OK",B,a+44,64);c(a,0,h)};k.onerror=function(n){K[a+40>>1]=4;K[a+42>>1]=413;A("Payload Too Large",B,a+44,64);d(a,0,n)}}catch(n){d(a,0,n)}}else d(a,0,"IndexedDB not available!")}
function Ed(a,b,c){var d=Bd;if(d){var f=M[a+112+64>>2];f||(f=M[a+8>>2]);f=G(f);try{var g=d.transaction(["FILES"],"readonly").objectStore("FILES").get(f);g.onsuccess=function(h){if(h.target.result){h=h.target.result;var k=h.byteLength||h.length,n=ub(k);B.set(new Uint8Array(h),n);M[a+12>>2]=n;Y(a+16,k);Y(a+24,0);Y(a+32,k);K[a+40>>1]=4;K[a+42>>1]=200;A("OK",B,a+44,64);b(a,0,h)}else K[a+40>>1]=4,K[a+42>>1]=404,A("Not Found",B,a+44,64),c(a,0,"no data")};g.onerror=function(h){K[a+40>>1]=4;K[a+42>>1]=404;
A("Not Found",B,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Fd(a,b,c){var d=Bd;if(d){var f=M[a+112+64>>2];f||(f=M[a+8>>2]);f=G(f);try{var g=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(f);g.onsuccess=function(h){h=h.target.result;M[a+12>>2]=0;Y(a+16,0);Y(a+24,0);Y(a+32,0);K[a+40>>1]=4;K[a+42>>1]=200;A("OK",B,a+44,64);b(a,0,h)};g.onerror=function(h){K[a+40>>1]=4;K[a+42>>1]=404;A("Not Found",B,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}var Gd={};
function Hd(){if(!Id){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea},b;for(b in Gd)a[b]=Gd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Id=c}return Id}var Id;function Jd(a){return 0===a%4&&(0!==a%100||0===a%400)}function Kd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Ld=[31,29,31,30,31,30,31,31,30,31,30,31],Md=[31,28,31,30,31,30,31,31,30,31,30,31];
function Nd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Jd(a.getFullYear())?Ld:Md)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Od(a,b,c,d){function f(l,p,x){for(l="number"===typeof l?l.toString():l||"";l.length<p;)l=x[0]+l;return l}function g(l,p){return f(l,p,"0")}function h(l,p){function x(H){return 0>H?-1:0<H?1:0}var F;0===(F=x(l.getFullYear()-p.getFullYear()))&&0===(F=x(l.getMonth()-p.getMonth()))&&(F=x(l.getDate()-p.getDate()));return F}function k(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),
0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function n(l){l=Nd(new Date(l.Hb+1900,0,1),l.hc);var p=new Date(l.getFullYear()+1,0,4),x=k(new Date(l.getFullYear(),0,4));p=k(p);return 0>=h(x,l)?0>=h(p,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var m=L[d+40>>2];d={Vc:L[d>>2],Uc:L[d+4>>2],fc:L[d+8>>2],Yb:L[d+12>>2],Tb:L[d+16>>2],Hb:L[d+20>>2],gc:L[d+24>>2],hc:L[d+28>>2],wd:L[d+32>>2],Tc:L[d+
36>>2],Wc:m?G(m):""};c=G(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in m)c=c.replace(new RegExp(q,"g"),m[q]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
y="January February March April May June July August September October November December".split(" ");m={"%a":function(l){return t[l.gc].substring(0,3)},"%A":function(l){return t[l.gc]},"%b":function(l){return y[l.Tb].substring(0,3)},"%B":function(l){return y[l.Tb]},"%C":function(l){return g((l.Hb+1900)/100|0,2)},"%d":function(l){return g(l.Yb,2)},"%e":function(l){return f(l.Yb,2," ")},"%g":function(l){return n(l).toString().substring(2)},"%G":function(l){return n(l)},"%H":function(l){return g(l.fc,
2)},"%I":function(l){l=l.fc;0==l?l=12:12<l&&(l-=12);return g(l,2)},"%j":function(l){return g(l.Yb+Kd(Jd(l.Hb+1900)?Ld:Md,l.Tb-1),3)},"%m":function(l){return g(l.Tb+1,2)},"%M":function(l){return g(l.Uc,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.fc&&12>l.fc?"AM":"PM"},"%S":function(l){return g(l.Vc,2)},"%t":function(){return"\t"},"%u":function(l){return l.gc||7},"%U":function(l){var p=new Date(l.Hb+1900,0,1),x=0===p.getDay()?p:Nd(p,7-p.getDay());l=new Date(l.Hb+1900,l.Tb,l.Yb);return 0>
h(x,l)?g(Math.ceil((31-x.getDate()+(Kd(Jd(l.getFullYear())?Ld:Md,l.getMonth()-1)-31)+l.getDate())/7),2):0===h(x,p)?"01":"00"},"%V":function(l){var p=new Date(l.Hb+1901,0,4),x=k(new Date(l.Hb+1900,0,4));p=k(p);var F=Nd(new Date(l.Hb+1900,0,1),l.hc);return 0>h(F,x)?"53":0>=h(p,F)?"01":g(Math.ceil((x.getFullYear()<l.Hb+1900?l.hc+32-x.getDate():l.hc+1-x.getDate())/7),2)},"%w":function(l){return l.gc},"%W":function(l){var p=new Date(l.Hb,0,1),x=1===p.getDay()?p:Nd(p,0===p.getDay()?1:7-p.getDay()+1);l=
new Date(l.Hb+1900,l.Tb,l.Yb);return 0>h(x,l)?g(Math.ceil((31-x.getDate()+(Kd(Jd(l.getFullYear())?Ld:Md,l.getMonth()-1)-31)+l.getDate())/7),2):0===h(x,p)?"01":"00"},"%y":function(l){return(l.Hb+1900).toString().substring(2)},"%Y":function(l){return l.Hb+1900},"%z":function(l){l=l.Tc;var p=0<=l;l=Math.abs(l)/60;return(p?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.Wc},"%%":function(){return"%"}};for(q in m)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),m[q](d)));q=
nb(c,!1);if(q.length>b)return 0;C.set(q,a);return q.length-1}var Pd;Wb();zb=Array(4096);Pb(R,"/");S("/tmp");S("/home");S("/home/web_user");
(function(){S("/dev");lb(259,{read:function(){return 0},write:function(c,d,f,g){return g}});Rb("/dev/null",259);kb(1280,ob);kb(1536,pb);Rb("/dev/tty",1280);Rb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}b||(b=function(){z("random_device")});Zb("random",b);Zb("urandom",b);S("/dev/shm");S("/dev/shm/tmp")})();S("/proc");S("/proc/self");S("/proc/self/fd");
Pb({Mb:function(){var a=rb("/proc/self","fd",16895,73);a.Db={Vb:function(b,c){var d=xb[+c];if(!d)throw new Q(8);b={parent:null,Mb:{zc:"fake"},Db:{Xb:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");for(var Qd=Array(256),Rd=0;256>Rd;++Rd)Qd[Rd]=String.fromCharCode(Rd);gc=Qd;nc=e.BindingError=mc("BindingError");oc=e.InternalError=mc("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};
e.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};Cc=e.UnboundTypeError=mc("UnboundTypeError");Pc=function(){return performance.now()};e.requestFullscreen=function(a,b,c){sd(a,b,c)};e.requestAnimationFrame=function(a){Xc(a)};e.setCanvasSize=function(a,b,c){ud(e.canvas,a,b);c||vd()};e.pauseMainLoop=function(){Uc=null;$c++};e.resumeMainLoop=function(){$c++;var a=Rc,b=Sc,c=Tc;Tc=null;Yc(c);Qc(a,b);Uc()};
e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};e.createContext=function(a,b,c,d){return od(a,b,c,d)};
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}})(function(a){Bd=a;Qa()},function(){Bd=!1;Qa()});"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||Pa();
function nb(a,b){var c=Array(wa(a)+1);a=A(a,c,0,c.length);b&&(c.length=a);return c}
var xe={m:function(a){return ub(a)},n:function(a){var b=O[a];b&&!b.pc&&(b.pc=!0,Sd.nc--);b&&(b.dc=!1);$a.push(a);(b=ab(a))&&O[b].Rb++;return a},p:function(){Z(0);var a=$a.pop();if(a){if(a=ab(a)){var b=O[a];b.Rb--;0!==b.Rb||b.dc||(b.sc&&e.dynCall_ii(b.sc,a),delete O[a],cb(a))}bb=0}},b:function(){var a=bb;if(!a)return w=0;var b=O[a],c=b.type;if(!c)return w=0,a|0;var d=Array.prototype.slice.call(arguments);Td(c);L[33780]=a;a=135120;for(var f=0;f<d.length;f++)if(d[f]&&Ud(d[f],c,a))return a=L[a>>2],b.ic.push(a),
w=d[f],a|0;a=L[a>>2];w=c;return a|0},h:function(){var a=bb;if(!a)return w=0;var b=O[a],c=b.type;if(!c)return w=0,a|0;var d=Array.prototype.slice.call(arguments);Td(c);L[33780]=a;a=135120;for(var f=0;f<d.length;f++)if(d[f]&&Ud(d[f],c,a))return a=L[a>>2],b.ic.push(a),w=d[f],a|0;a=L[a>>2];w=c;return a|0},q:cb,R:function(){var a=$a.pop();a=ab(a);O[a].dc||($a.push(a),O[a].dc=!0);bb=a;throw a;},r:function(a,b,c){O[a]={Oc:a,ic:[a],type:b,sc:c,Rb:0,pc:!1,dc:!1};bb=a;"uncaught_exception"in Sd?Sd.nc++:Sd.nc=
1;throw a;},ra:function(){return Sd.nc},M:function(){},ka:function(){db(63);return-1},c:function(a){bb||(bb=a);throw a;},ja:function(a,b){cc=b;try{var c=dc(),d=dc();if(-1===c||0===d)var f=-28;else{var g=bc[c];if(g&&d===g.nd){var h=xb[g.Pb],k=g.flags,n=g.offset,m=new Uint8Array(B.subarray(c,c+d));h&&h.Eb.bc&&h.Eb.bc(h,m,n,d,k);bc[c]=null;g.Fc&&P(g.qd)}f=0}return f}catch(q){return"undefined"!==typeof ac&&q instanceof Q||z(q),-q.Ub}},D:function(){},ga:function(a,b,c,d,f){var g=fc(c);b=T(b);W(a,{name:b,
fromWireType:function(h){return!!h},toWireType:function(h,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var k=C;else if(2===c)k=ya;else if(4===c)k=L;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[h>>g])},Nb:null})},ea:function(a,b){b=T(b);W(a,{name:b,fromWireType:function(c){var d=X[c].value;rc(c);return d},toWireType:function(c,d){return sc(d)},argPackAdvance:8,readValueFromPointer:tc,Nb:null})},G:function(a,b,c){c=fc(c);b=T(b);
W(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+uc(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:vc(b,c),Nb:null})},Ba:function(a,b,c,d,f,g){var h=Ac(b,c);a=T(a);f=Bc(d,f);zc(a,function(){Fc("Cannot call "+a+" due to unbound types",h)},b-1);pc(h,function(k){var n=a,m=a;k=[k[0],null].concat(k.slice(1));var q=f,t=k.length;2>t&&U("argTypes array size mismatch! Must at least get return value and 'this' types!");
for(var y=null!==k[1]&&!1,l=!1,p=1;p<k.length;++p)if(null!==k[p]&&void 0===k[p].Nb){l=!0;break}var x="void"!==k[0].name,F="",H="";for(p=0;p<t-2;++p)F+=(0!==p?", ":"")+"arg"+p,H+=(0!==p?", ":"")+"arg"+p+"Wired";m="return function "+kc(m)+"("+F+") {\nif (arguments.length !== "+(t-2)+") {\nthrowBindingError('function "+m+" called with ' + arguments.length + ' arguments, expected "+(t-2)+" args!');\n}\n";l&&(m+="var destructors = [];\n");var V=l?"destructors":"null";F="throwBindingError invoker fn runDestructors retType classParam".split(" ");
q=[U,q,g,xc,k[0],k[1]];y&&(m+="var thisWired = classParam.toWireType("+V+", this);\n");for(p=0;p<t-2;++p)m+="var arg"+p+"Wired = argType"+p+".toWireType("+V+", arg"+p+"); // "+k[p+2].name+"\n",F.push("argType"+p),q.push(k[p+2]);y&&(H="thisWired"+(0<H.length?", ":"")+H);m+=(x?"var rv = ":"")+"invoker(fn"+(0<H.length?", ":"")+H+");\n";if(l)m+="runDestructors(destructors);\n";else for(p=y?1:2;p<k.length;++p)t=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==k[p].Nb&&(m+=t+"_dtor("+t+"); // "+k[p].name+"\n",
F.push(t+"_dtor"),q.push(k[p].Nb));x&&(m+="var ret = retType.fromWireType(rv);\nreturn ret;\n");F.push(m+"}\n");k=wc(F).apply(null,q);p=b-1;if(!e.hasOwnProperty(n))throw new oc("Replacing nonexistant public symbol");void 0!==e[n].Kb&&void 0!==p?e[n].Kb[p]=k:(e[n]=k,e[n].Gc=p);return[]})},y:function(a,b,c,d,f){function g(m){return m}b=T(b);-1===f&&(f=4294967295);var h=fc(c);if(0===d){var k=32-8*c;g=function(m){return m<<k>>>k}}var n=-1!=b.indexOf("unsigned");W(a,{name:b,fromWireType:g,toWireType:function(m,
q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+uc(q)+'" to '+this.name);if(q<d||q>f)throw new TypeError('Passing a number "'+uc(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return n?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:Gc(b,h,0!==d),Nb:null})},w:function(a,b,c){function d(g){g>>=2;return new f(M.buffer,M[g+1],M[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=T(c);W(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Kc:!0})},H:function(a,b){b=T(b);var c="std::string"===b;W(a,{name:b,fromWireType:function(d){var f=M[d>>2];if(c){var g=B[d+4+f],h=0;0!=g&&(h=g,B[d+4+f]=0);var k=d+4;for(g=0;g<=f;++g){var n=d+4+g;if(0==B[n]){k=G(k);if(void 0===m)var m=k;else m+=String.fromCharCode(0),m+=k;k=n+1}}0!=h&&(B[d+4+f]=h)}else{m=Array(f);for(g=0;g<f;++g)m[g]=String.fromCharCode(B[d+4+g]);m=m.join("")}P(d);
return m},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||U("Cannot pass non-string to std::string");var h=(c&&g?function(){return wa(f)}:function(){return f.length})(),k=ub(4+h+1);M[k>>2]=h;if(c&&g)A(f,B,k+4,h+1);else if(g)for(g=0;g<h;++g){var n=f.charCodeAt(g);255<n&&(P(k),U("String has UTF-16 code units that do not fit in 8 bits"));B[k+4+g]=n}else for(g=0;g<h;++g)B[k+
4+g]=f[g];null!==d&&d.push(P,k);return k},argPackAdvance:8,readValueFromPointer:tc,Nb:function(d){P(d)}})},fa:function(a,b,c){c=T(c);if(2===b){var d=function(){return K};var f=1}else 4===b&&(d=function(){return M},f=2);W(a,{name:c,fromWireType:function(g){for(var h=d(),k=M[g>>2],n=Array(k),m=g+4>>f,q=0;q<k;++q)n[q]=String.fromCharCode(h[m+q]);P(g);return n.join("")},toWireType:function(g,h){var k=h.length,n=ub(4+k*b),m=d();M[n>>2]=k;for(var q=n+4>>f,t=0;t<k;++t)m[q+t]=h.charCodeAt(t);null!==g&&g.push(P,
n);return n},argPackAdvance:8,readValueFromPointer:tc,Nb:function(g){P(g)}})},ha:function(a,b){b=T(b);W(a,{Lc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},ba:function(a){delete Ad[a-1]},P:function(a,b,c){a=Hc(a);b=Ic(b,"emval::as");var d=[],f=sc(d);L[c>>2]=f;return b.toWireType(d,a)},O:function(a,b,c,d,f){a=Lc[a];b=Hc(b);c=Kc(c);var g=[];L[d>>2]=sc(g);return a(b,c,g,f)},Ca:rc,ya:function(a){if(0===a)return sc(Mc());a=Kc(a);return sc(Mc()[a])},N:function(a,b){b=Oc(a,
b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(m){return m.name}).join("_")+"$",f=["retType"],g=[c],h="",k=0;k<a-1;++k)h+=(0!==k?", ":"")+"arg"+k,f.push("argType"+k),g.push(b[1+k]);d="return function "+kc("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var n=0;for(k=0;k<a-1;++k)d+="    var arg"+k+" = argType"+k+".readValueFromPointer(args"+(n?"+"+n:"")+");\n",n+=b[k+1].argPackAdvance;d+="    var rv = handle[name]("+h+");\n";for(k=0;k<a-1;++k)b[k+1].deleteObject&&(d+="    argType"+
k+".deleteObject(arg"+k+");\n");c.Lc||(d+="    return retType.toWireType(destructors, rv);\n");f.push(d+"};\n");a=wc(f).apply(null,g);return Nc(a)},Aa:function(a,b){a=Hc(a);b=Hc(b);return sc(a[b])},Q:function(a){4<a&&(X[a].Rb+=1)},va:function(a){return sc(Kc(a))},ua:function(a){xc(X[a].value);rc(a)},xa:function(a,b,c){a=Hc(a);b=Hc(b);c=Hc(c);a[b]=c},wa:function(a,b){a=Hc(a);b=Hc(b);return a===b},E:function(a,b){a=Ic(a,"_emval_take_value");a=a.readValueFromPointer(b);return sc(a)},I:function(){z()},
sa:function(a,b){if(0===a)a=Date.now();else if(1===a)a=Pc();else return db(28),-1;L[b>>2]=a/1E3|0;L[b+4>>2]=a%1E3*1E6|0;return 0},u:function(a,b,c){Pd||(Pd=[]);var d=Pd;d.length=0;for(var f;f=B[b++];)100===f||102===f?(c=c+7&-8,d.push(Aa[c>>3]),c+=8):(c=c+3&-4,d.push(L[c>>2]),c+=4);return Ya[a].apply(null,d)},ta:function(a,b,c){function d(){ka(a)(b)}na=!0;0<=c?nd(d,c):yd(d)},da:function(){return!0},$:function(a,b,c){B.set(B.subarray(b,b+c),a)},aa:function(){z("OOM")},ca:function(a,b,c,d,f){function g(D){Cd(D,
h,m,q,n)}function h(D,ba){Dd(D,ba.response,function(ca){p?Vd(p,ca):b&&b(ca)},function(ca){p?Vd(p,ca):b&&b(ca)})}function k(D){Cd(D,t,m,q,n)}function n(D){H?Vd(H,D):f&&f(D)}function m(D){x?Vd(x,D):c&&c(D)}function q(D){F?Vd(F,D):d&&d(D)}function t(D){p?Vd(p,D):b&&b(D)}"undefined"!==typeof na&&(na=!0);var y=a+112,l=G(y),p=M[y+36>>2],x=M[y+40>>2],F=M[y+44>>2],H=M[y+48>>2],V=M[y+52>>2],u=!!(V&4),I=!!(V&32);V=!!(V&16);if("EM_IDB_STORE"===l)l=M[y+84>>2],Dd(a,B.slice(l,l+M[y+88>>2]),t,m);else if("EM_IDB_DELETE"===
l)Fd(a,t,m);else if(V){if(I)return 0;Cd(a,u?h:t,m,q,n)}else Ed(a,t,I?m:u?g:k);return a},la:function(a,b){var c=0;Hd().forEach(function(d,f){var g=b+c;f=L[a+4*f>>2]=g;for(g=0;g<d.length;++g)C[f++>>0]=d.charCodeAt(g);C[f>>0]=0;c+=d.length+1});return 0},ma:function(a,b){var c=Hd();L[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});L[b>>2]=d;return 0},pa:function(a){try{var b=ec(a);if(null===b.Pb)throw new Q(8);b.kc&&(b.kc=null);try{b.Eb.close&&b.Eb.close(b)}catch(c){throw c;}finally{xb[b.Pb]=
null}b.Pb=null;return 0}catch(c){return"undefined"!==typeof ac&&c instanceof Q||z(c),c.Ub}},oa:function(a,b,c,d){try{a:{for(var f=ec(a),g=a=0;g<c;g++){var h=L[b+(8*g+4)>>2],k=f,n=L[b+8*g>>2],m=h,q=void 0,t=C;if(0>m||0>q)throw new Q(28);if(null===k.Pb)throw new Q(8);if(1===(k.flags&2097155))throw new Q(8);if(16384===(k.node.mode&61440))throw new Q(31);if(!k.Eb.read)throw new Q(28);var y="undefined"!==typeof q;if(!y)q=k.position;else if(!k.seekable)throw new Q(70);var l=k.Eb.read(k,t,n,m,q);y||(k.position+=
l);var p=l;if(0>p){var x=-1;break a}a+=p;if(p<h)break}x=a}L[d>>2]=x;return 0}catch(F){return"undefined"!==typeof ac&&F instanceof Q||z(F),F.Ub}},Y:function(a,b,c,d,f){try{var g=ec(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Vb(g,a,d);Xa=[g.position>>>0,(Wa=g.position,1<=+Ia(Wa)?0<Wa?(La(+Ka(Wa/4294967296),4294967295)|0)>>>0:~~+Ja((Wa-+(~~Wa>>>0))/4294967296)>>>0:0)];L[f>>2]=Xa[0];L[f+4>>2]=Xa[1];g.kc&&0===a&&0===d&&(g.kc=null);return 0}catch(h){return"undefined"!==
typeof ac&&h instanceof Q||z(h),h.Ub}},na:function(a,b,c,d){try{a:{for(var f=ec(a),g=a=0;g<c;g++){var h=f,k=L[b+8*g>>2],n=L[b+(8*g+4)>>2],m=void 0,q=C;if(0>n||0>m)throw new Q(28);if(null===h.Pb)throw new Q(8);if(0===(h.flags&2097155))throw new Q(8);if(16384===(h.node.mode&61440))throw new Q(31);if(!h.Eb.write)throw new Q(28);h.flags&1024&&Vb(h,0,2);var t="undefined"!==typeof m;if(!t)m=h.position;else if(!h.seekable)throw new Q(70);var y=h.Eb.write(h,q,k,n,m,void 0);t||(h.position+=y);try{if(h.path&&
Bb.onWriteToFile)Bb.onWriteToFile(h.path)}catch(x){v("FS.trackingDelegate['onWriteToFile']('"+h.path+"') threw an exception: "+x.message)}var l=y;if(0>l){var p=-1;break a}a+=l}p=a}L[d>>2]=p;return 0}catch(x){return"undefined"!==typeof ac&&x instanceof Q||z(x),x.Ub}},a:function(){return w|0},J:Wd,K:Xd,s:Yd,e:Zd,W:$d,S:ae,f:be,j:ce,k:de,qa:ee,U:fe,x:ge,L:he,B:ie,_:je,Z:ke,X:le,l:me,o:ne,za:oe,d:pe,F:qe,g:re,i:se,t:te,v:ue,z:ve,A:we,V:function(a){return a},memory:oa,T:function(a){a=+a;return 0<=a?+Ka(a+
.5):+Ja(a-.5)},C:function(a){w=a|0},ia:function(a,b,c,d){return Od(a,b,c,d)},table:pa},ye=function(){function a(f){e.asm=f.exports;Qa()}function b(f){a(f.instance)}function c(f){return Va().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){v("failed to asynchronously prepare wasm: "+g);z(g)})}var d={a:xe};Pa();if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return v("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(ma||"function"!==
typeof WebAssembly.instantiateStreaming||Ra()||"function"!==typeof fetch)return c(b);fetch(Sa,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){v("wasm streaming compile failed: "+g);v("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();e.asm=ye;
var Za=e.___wasm_call_ctors=function(){return(Za=e.___wasm_call_ctors=e.asm.Da).apply(null,arguments)},Sd=e.__ZSt18uncaught_exceptionv=function(){return(Sd=e.__ZSt18uncaught_exceptionv=e.asm.Ea).apply(null,arguments)};e._init_demo=function(){return(e._init_demo=e.asm.Fa).apply(null,arguments)};e.___errno_location=function(){return(e.___errno_location=e.asm.Ga).apply(null,arguments)};
var ub=e._malloc=function(){return(ub=e._malloc=e.asm.Ha).apply(null,arguments)},Z=e._setThrew=function(){return(Z=e._setThrew=e.asm.Ia).apply(null,arguments)},P=e._free=function(){return(P=e._free=e.asm.Ja).apply(null,arguments)},Ud=e.___cxa_can_catch=function(){return(Ud=e.___cxa_can_catch=e.asm.Ka).apply(null,arguments)},Td=e.___cxa_is_pointer_type=function(){return(Td=e.___cxa_is_pointer_type=e.asm.La).apply(null,arguments)},Ec=e.___getTypeName=function(){return(Ec=e.___getTypeName=e.asm.Ma).apply(null,
arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.Na).apply(null,arguments)};
var ze=e.dynCall_v=function(){return(ze=e.dynCall_v=e.asm.Oa).apply(null,arguments)},Vd=e.dynCall_vi=function(){return(Vd=e.dynCall_vi=e.asm.Pa).apply(null,arguments)},Ae=e.dynCall_vii=function(){return(Ae=e.dynCall_vii=e.asm.Qa).apply(null,arguments)},Be=e.dynCall_viii=function(){return(Be=e.dynCall_viii=e.asm.Ra).apply(null,arguments)},Ce=e.dynCall_viiii=function(){return(Ce=e.dynCall_viiii=e.asm.Sa).apply(null,arguments)},De=e.dynCall_viiiii=function(){return(De=e.dynCall_viiiii=e.asm.Ta).apply(null,
arguments)},Ee=e.dynCall_viiiiiii=function(){return(Ee=e.dynCall_viiiiiii=e.asm.Ua).apply(null,arguments)},Fe=e.dynCall_viiiiiiiiii=function(){return(Fe=e.dynCall_viiiiiiiiii=e.asm.Va).apply(null,arguments)},Ge=e.dynCall_viiiiiiiiiiiiiii=function(){return(Ge=e.dynCall_viiiiiiiiiiiiiii=e.asm.Wa).apply(null,arguments)},He=e.dynCall_viid=function(){return(He=e.dynCall_viid=e.asm.Xa).apply(null,arguments)},Ie=e.dynCall_vid=function(){return(Ie=e.dynCall_vid=e.asm.Ya).apply(null,arguments)},Je=e.dynCall_i=
function(){return(Je=e.dynCall_i=e.asm.Za).apply(null,arguments)},Ke=e.dynCall_ii=function(){return(Ke=e.dynCall_ii=e.asm._a).apply(null,arguments)},Le=e.dynCall_iii=function(){return(Le=e.dynCall_iii=e.asm.$a).apply(null,arguments)},Me=e.dynCall_iiii=function(){return(Me=e.dynCall_iiii=e.asm.ab).apply(null,arguments)},Ne=e.dynCall_iiiii=function(){return(Ne=e.dynCall_iiiii=e.asm.bb).apply(null,arguments)},Oe=e.dynCall_iiiiii=function(){return(Oe=e.dynCall_iiiiii=e.asm.cb).apply(null,arguments)},
Pe=e.dynCall_iiiiiii=function(){return(Pe=e.dynCall_iiiiiii=e.asm.db).apply(null,arguments)},Qe=e.dynCall_iiiiiiii=function(){return(Qe=e.dynCall_iiiiiiii=e.asm.eb).apply(null,arguments)};e.dynCall_iiiiiiiiiii=function(){return(e.dynCall_iiiiiiiiiii=e.asm.fb).apply(null,arguments)};var Re=e.dynCall_iiiiiiiiiiii=function(){return(Re=e.dynCall_iiiiiiiiiiii=e.asm.gb).apply(null,arguments)};e.dynCall_iiiiiiiiiiiii=function(){return(e.dynCall_iiiiiiiiiiiii=e.asm.hb).apply(null,arguments)};
var Se=e.dynCall_iiiiid=function(){return(Se=e.dynCall_iiiiid=e.asm.ib).apply(null,arguments)},Te=e.dynCall_iij=function(){return(Te=e.dynCall_iij=e.asm.jb).apply(null,arguments)},Ue=e.dynCall_iid=function(){return(Ue=e.dynCall_iid=e.asm.kb).apply(null,arguments)},Ve=e.dynCall_iidi=function(){return(Ve=e.dynCall_iidi=e.asm.lb).apply(null,arguments)};e.dynCall_id=function(){return(e.dynCall_id=e.asm.mb).apply(null,arguments)};
var We=e.dynCall_jii=function(){return(We=e.dynCall_jii=e.asm.nb).apply(null,arguments)},Xe=e.dynCall_jiiii=function(){return(Xe=e.dynCall_jiiii=e.asm.ob).apply(null,arguments)},Ye=e.dynCall_fiii=function(){return(Ye=e.dynCall_fiii=e.asm.pb).apply(null,arguments)},Ze=e.dynCall_diii=function(){return(Ze=e.dynCall_diii=e.asm.qb).apply(null,arguments)},E=e.stackSave=function(){return(E=e.stackSave=e.asm.rb).apply(null,arguments)},ta=e.stackAlloc=function(){return(ta=e.stackAlloc=e.asm.sb).apply(null,
arguments)},J=e.stackRestore=function(){return(J=e.stackRestore=e.asm.tb).apply(null,arguments)};e.dynCall_viijii=function(){return(e.dynCall_viijii=e.asm.ub).apply(null,arguments)};e.dynCall_iidiiii=function(){return(e.dynCall_iidiiii=e.asm.vb).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.wb).apply(null,arguments)};e.dynCall_iiiiiiiii=function(){return(e.dynCall_iiiiiiiii=e.asm.xb).apply(null,arguments)};
e.dynCall_iiiiij=function(){return(e.dynCall_iiiiij=e.asm.yb).apply(null,arguments)};e.dynCall_iiiiijj=function(){return(e.dynCall_iiiiijj=e.asm.zb).apply(null,arguments)};e.dynCall_iiiiiijj=function(){return(e.dynCall_iiiiiijj=e.asm.Ab).apply(null,arguments)};e.dynCall_viiiiii=function(){return(e.dynCall_viiiiii=e.asm.Bb).apply(null,arguments)};function be(a,b,c){var d=E();try{return Le(a,b,c)}catch(f){J(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}
function re(a,b,c,d){var f=E();try{Be(a,b,c,d)}catch(g){J(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function pe(a,b,c){var d=E();try{Ae(a,b,c)}catch(f){J(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function $d(a,b,c){var d=E();try{return Ue(a,b,c)}catch(f){J(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function Zd(a,b){var c=E();try{return Ke(a,b)}catch(d){J(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}
function ce(a,b,c,d){var f=E();try{return Me(a,b,c,d)}catch(g){J(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function Yd(a){var b=E();try{return Je(a)}catch(c){J(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}}function fe(a,b,c,d,f,g){var h=E();try{return Oe(a,b,c,d,f,g)}catch(k){J(h);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function ne(a,b){var c=E();try{Vd(a,b)}catch(d){J(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}
function me(a){var b=E();try{ze(a)}catch(c){J(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}}function se(a,b,c,d,f){var g=E();try{Ce(a,b,c,d,f)}catch(h){J(g);if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}}function te(a,b,c,d,f,g){var h=E();try{De(a,b,c,d,f,g)}catch(k){J(h);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function de(a,b,c,d,f){var g=E();try{return Ne(a,b,c,d,f)}catch(h){J(g);if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}}
function ge(a,b,c,d,f,g,h){var k=E();try{return Pe(a,b,c,d,f,g,h)}catch(n){J(k);if(n!==n+0&&"longjmp"!==n)throw n;Z(1,0)}}function ae(a,b,c,d){var f=E();try{return Ve(a,b,c,d)}catch(g){J(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function qe(a,b,c,d){var f=E();try{He(a,b,c,d)}catch(g){J(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function oe(a,b,c){var d=E();try{Ie(a,b,c)}catch(f){J(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}
function ee(a,b,c,d,f,g){var h=E();try{return Se(a,b,c,d,f,g)}catch(k){J(h);if(k!==k+0&&"longjmp"!==k)throw k;Z(1,0)}}function he(a,b,c,d,f,g,h,k){var n=E();try{return Qe(a,b,c,d,f,g,h,k)}catch(m){J(n);if(m!==m+0&&"longjmp"!==m)throw m;Z(1,0)}}function Xd(a,b,c,d){var f=E();try{return Ye(a,b,c,d)}catch(g){J(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function Wd(a,b,c,d){var f=E();try{return Ze(a,b,c,d)}catch(g){J(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}
function ue(a,b,c,d,f,g,h,k){var n=E();try{Ee(a,b,c,d,f,g,h,k)}catch(m){J(n);if(m!==m+0&&"longjmp"!==m)throw m;Z(1,0)}}function ie(a,b,c,d,f,g,h,k,n,m,q,t){var y=E();try{return Re(a,b,c,d,f,g,h,k,n,m,q,t)}catch(l){J(y);if(l!==l+0&&"longjmp"!==l)throw l;Z(1,0)}}function ve(a,b,c,d,f,g,h,k,n,m,q){var t=E();try{Fe(a,b,c,d,f,g,h,k,n,m,q)}catch(y){J(t);if(y!==y+0&&"longjmp"!==y)throw y;Z(1,0)}}
function we(a,b,c,d,f,g,h,k,n,m,q,t,y,l,p,x){var F=E();try{Ge(a,b,c,d,f,g,h,k,n,m,q,t,y,l,p,x)}catch(H){J(F);if(H!==H+0&&"longjmp"!==H)throw H;Z(1,0)}}function je(a,b,c,d){var f=E();try{return Te(a,b,c,d)}catch(g){J(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function ke(a,b,c){var d=E();try{return We(a,b,c)}catch(f){J(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function le(a,b,c,d,f){var g=E();try{return Xe(a,b,c,d,f)}catch(h){J(g);if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}}e.asm=ye;e.ccall=sa;
e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(g){return"number"===g});return"string"!==b&&f&&!d?ra(a):function(){return sa(a,b,c,arguments,d)}};e.UTF8ToString=G;var $e;e.then=function(a){if($e)a(e);else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=function(){b&&b();a(e)}}return e};Oa=function af(){$e||bf();$e||(Oa=af)};
function bf(){function a(){if(!$e&&($e=!0,!qa)){e.noFSInit||Xb||(Xb=!0,Wb(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?Zb("stdin",e.stdin):Sb("/dev/tty","/dev/stdin"),e.stdout?Zb("stdout",null,e.stdout):Sb("/dev/tty","/dev/stdout"),e.stderr?Zb("stderr",null,e.stderr):Sb("/dev/tty1","/dev/stderr"),Tb("/dev/stdin","r"),Tb("/dev/stdout","w"),Tb("/dev/stderr","w"));Ca(Ea);Ab=!1;Ca(Fa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=
[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Ga.unshift(b)}Ca(Ga)}}if(!(0<Ma)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ha();Ca(Da);0<Ma||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=bf;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();na=!0;bf();


  return AliaDemos
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = AliaDemos;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return AliaDemos; });
    else if (typeof exports === 'object')
      exports["AliaDemos"] = AliaDemos;
    